### PR TITLE
simplest fix for ї glyph in 拾陆字濑户2.0-1 font, and proper line positioning

### PR DESCRIPTION
**Pull request by Blackflexxy**
image
image

### CODE REVIEW

**Comment by nestor-churin** [comment]
Можете будь ласка підказати в якій локації це відбулося?

**Comment by nestor-churin** [comment]
> image image

Можете будь ласка підказати в якій локації це відбулося?

**Comment by nestor-churin** [comment]
Fixed

**Comment by Blackflexxy** [comment]
Still an issue.
image
Theoretically, because this font is under SIL Open Font License, we can modify it, and assign that glyph to proper cyrillic ї character. But that would modify resource files, so updated font should be pushed to developers if possible

**Comment by nestor-churin** [comment]
It would be great to contact the developer, but I'm not sure they would agree to the changes since this issue doesn't occur in the translation test including with one of the developers.

**Comment by nestor-churin** [comment]
> Still an issue. image Theoretically, because this font is under SIL Open Font License, we can modify it, and assign that glyph to proper cyrillic ї character. But that would modify resource files, so updated font should be pushed to developers if possible

It would be great to contact the developer, but I'm not sure they would agree to the changes since this issue doesn't occur in the translation test including with one of the developers.

**Comment by nestor-churin** [comment]
{A08C72A2-FB2B-44F3-98F9-EF9DAA0F377E}

**Comment by Blackflexxy** [comment]
> this issue doesn't occur in the translation test

which translation test?

**Comment by nestor-churin** [comment]
> > this issue doesn't occur in the translation test
> 
> which translation test?

There was a test recently. And now the developers are checking its translation, so here I just write in the steam discussion that there is no font for the letter "Ї". It doesn't depend on us now

**Pull request closed without merging**
